version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "rec-hentai"
    labels:
      - "triage-required"
      - "dependencies"
    commit-message:
      prefix: "[MAINT]"
    assignees:
      - "hentai-chan"
    reviewers:
      - "hentai-chan"
